services:
  sqlserver:
    ports:
      - "1433:1433"

  gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__identity-cluster__Destinations__destination1__Address=http://identityservice.api:8080
      - ReverseProxy__Clusters__tasks-cluster__Destinations__destination1__Address=http://tasksservice.api:8080
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5003:8080"

  identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=IdentityDB;User Id=sa;Password=YOUR_SA_PASSWORD;TrustServerCertificate=True;
      - JwtSettings__SecretKey=YOUR_JWT_SECRET_KEY
    ports:
      - "5001:8080"

  tasksservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TasksDB;User Id=sa;Password=YOUR_SA_PASSWORD;TrustServerCertificate=True;
      - JwtSettings__SecretKey=YOUR_JWT_SECRET_KEY
    ports:
      - "5002:8080"
